version: 2
jobs:
  lint:
    working_directory: ~/project
    docker:
      - image: girder/girder_test:latest-py3
      - image: circleci/mongo:3.4-ram
        # storage engine. We can pass alternate options to "mongod" by overwriting the default "CMD"
        # used to start the Docker image: https://github.com/circleci/circleci-images/blob/master/mongo/resources/Dockerfile-ram.template
        command: ["mongod", "--storageEngine", "ephemeralForTest", "--dbpath", "/dev/shm/mongo"]

    steps:
      - checkout
      - run:
          name: Run tests via tox
          # Piping through cat does less buffering of the output but can
          # consume the exit code
          command: tox -e flake8,lintclient  | cat; test ${PIPESTATUS[0]} -eq 0
      # - run:
      #     name: Install Codecov client
      #     command: pip install codecov
      # - run:
      #     name: Upload coverage
      #     # Retry as codecov can be flaky
      #     command: for i in $(seq 1 10); do [ %i -gt 1 ] && echo "retrying $i" && sleep 5; codecov --required --disable search pycov gcov --root project --file build/test/coverage/py_coverage.xml build/test/coverage/cobertura-coverage.xml && s=0 && break || s=$?; done; (exit $s)
  py27:
    working_directory: ~/project
    docker:
      - image: girder/girder_test:latest-py2
      - image: circleci/mongo:3.4-ram
        # storage engine. We can pass alternate options to "mongod" by overwriting the default "CMD"
        # used to start the Docker image: https://github.com/circleci/circleci-images/blob/master/mongo/resources/Dockerfile-ram.template
        command: ["mongod", "--storageEngine", "ephemeralForTest", "--dbpath", "/dev/shm/mongo"]
    steps:
      - checkout
      - run:
          name: Run tests via tox
          command: tox -e py27 | cat; test ${PIPESTATUS[0]} -eq 0
  py36:
    working_directory: ~/project
    docker:
      - image: girder/girder_test:latest-py3
      - image: circleci/mongo:3.4-ram
        # storage engine. We can pass alternate options to "mongod" by overwriting the default "CMD"
        # used to start the Docker image: https://github.com/circleci/circleci-images/blob/master/mongo/resources/Dockerfile-ram.template
        command: ["mongod", "--storageEngine", "ephemeralForTest", "--dbpath", "/dev/shm/mongo"]
    steps:
      - checkout
      - run:
          name: Run tests via tox
          command: tox -e py36 | cat; test ${PIPESTATUS[0]} -eq 0
  py37:
    working_directory: ~/project
    docker:
      - image: girder/girder_test:latest-py3
      - image: circleci/mongo:3.4-ram
        # storage engine. We can pass alternate options to "mongod" by overwriting the default "CMD"
        # used to start the Docker image: https://github.com/circleci/circleci-images/blob/master/mongo/resources/Dockerfile-ram.template
        command: ["mongod", "--storageEngine", "ephemeralForTest", "--dbpath", "/dev/shm/mongo"]
    steps:
      - checkout
      - run:
          name: Run tests via tox
          command: tox -e py37 | cat; test ${PIPESTATUS[0]} -eq 0
workflows:
  version: 2
  ci:
    jobs:
      - lint:
          filters:
            tags:
              only: /^v.*/
      # - py27:
      #     filters:
      #       tags:
      #         only: /^v.*/
      # - py36:
      #     filters:
      #       tags:
      #         only: /^v.*/
      - py37:
          filters:
            tags:
              only: /^v.*/
